const randomStok = () => {
  const stock = parseInt(Math.random(1, 100) * 20000 * 1000);
  return stock;
};
const randomPrice = () => {
  const price = parseInt(Math.random(1, 100) * 10 * 50);
  return price;
};

const listProducts = [
  "Televisor 4K",
  "Laptop Gaming",
  "Smartphone",
  "Tableta",
  "Reloj Inteligente",
  "Cámara de Seguridad",
  "Altavoces Bluetooth",
  "Consola de Juegos",
  "Videojuegos",
  "Pantalones de Vestir",
  "Camisas de Manga Larga",
  "Zapatillas de Deporte",
  "Bolsas de Moda",
  "Joyas de Lujo",
  "Perfumes de Mujer",
  "Perfumes de Hombre",
  "Maquillaje",
  "Cremas de Belleza",
  "Champú y Acondicionador",
  "Cepillos de Dientes",
  "Pastas de Dientes",
  "Jabones de Baño",
  "Toallas de Baño",
  "Sábanas y Fundas",
  "Almohadas y Edredones",
  "Muebles de Oficina",
  "Sillas de Oficina",
  "Escritorios",
  "Archivadores",
  "Impresoras",
  "Scanners",
  "Fotocopiadoras",
  "Cafeteras",
  "Tostadoras",
  "Microondas",
  "Licuadoras",
  "Batidoras",
  "Hornos Eléctricos",
  "Parrillas Eléctricas",
  "Cocinas de Inducción",
  "Refrigeradores",
  "Congeladores",
  "Lavadoras",
  "Secadoras",
  "Aspiradoras",
  "Trapos de Limpieza",
  "Detergentes",
  "Suavizantes",
  "Juguetes de Niños",
  "Juegos de Mesa",
  "Puzzles",
  "Libros de Cuentos",
  "Libros de Historia",
  "Libros de Ciencia",
  "Libros de Ficción",
  "Música en CD",
  "Películas en DVD",
  "Series de TV en DVD",
  "Instrumentos Musicales",
  "Accesorios de Música",
  "Equipo de Deporte",
  "Bicicletas",
  "Patines",
  "Skateboards",
  "Pelotas de Fútbol",
  "Pelotas de Baloncesto",
  "Pelotas de Tenis",
  "Raquetas de Tenis",
  "Guantes de Béisbol",
  "Bates de Béisbol",
  "Cascos de Fútbol",
  "Protuberancias de Fútbol",
  "Rodilleras de Fútbol",
  "Guantes de Fútbol",
  "Balones de Fútbol",
  "Pelotas de Golf",
  "Palos de Golf",
  "Guantes de Golf",
  "Zapatillas de Golf",
  "Pelotas de Tenis de Mesa",
  "Raquetas de Tenis de Mesa",
  "Mesas de Tenis de Mesa",
  "Sillas de Oficina Ergonómicas",
  "Muebles de Jardín",
  "Herramientas de Jardinería",
  "Semillas de Flores",
  "Semillas de Verduras",
  "Abonos para Plantas",
  "Pesticidas para Plantas",
  "Riegos para Plantas",
  "Macetas de Cerámica",
  "Macetas de Plástico",
  "Cajas de Madera",
  "Cajas de Plástico",
  "Bolsas de Papel",
  "Bolsas de Plástico",
  "Cintas Adhesivas",
  "Cintas de Embalar",
  "Papel de Regalo",
  "Tarjetas de Felicitación",
  "Calendarios de Pareja",
  "Calendarios de Viaje",
  "Libros de Cocina",
  "Libros de Nutrición",
  "Libros de Fitness",
  "Libros de Meditación",
  "Libros de Autoayuda",
  "Libros de Historia Universal",
  "Libros de Ciencia Ficción",
  "Libros de Fantasía",
  "Libros de Misterio",
  "Libros de Romance",
  "Libros de Terror",
  "Películas de Acción",
  "Películas de Comedia",
  "Películas de Drama",
  "Películas de Romance",
  "Películas de Terror",
  "Series de TV de Comedia",
  "Series de TV de Drama",
  "Series de TV de Ciencia Ficción",
  "Series de TV de Fantasía",
  "Instrumentos Musicales de Cuerda",
  "Instrumentos Musicales de Viento",
  "Instrumentos Musicales de Percusión",
  "Accesorios de Música para Guitarra",
  "Accesorios de Música para Batería",
  "Equipo de Deporte para Fútbol",
  "Equipo de Deporte para Baloncesto",
  "Equipo de Deporte para Tenis",
  "Equipo de Deporte para Golf",
  "Bicicletas de Carretera",
  "Bicicletas de Montaña",
  "Bicicletas de Pista",
  "Patines de Hielo",
  "Patines de Rueda",
  "Skateboards de Calle",
  "Skateboards de Parque",
  "Pelotas de Fútbol de Salón",
  "Pelotas de Baloncesto de Salón",
  "Pelotas de Tenis de Salón",
  "Raquetas de Tenis de Salón",
  "Guantes de Béisbol de Salón",
  "Bates de Béisbol de Salón",
  "Cascos de Fútbol de Salón",
  "Protuberancias de Fútbol de Salón",
  "Rodilleras de Fútbol de Salón",
  "Guantes de Fútbol de Salón",
  "Balones de Fútbol de Salón",
  "Pantalones de Vestir para Hombre",
  "Pantalones de Vestir para Mujer",
  "Vestidos de Fiesta para Mujer",
  "Trajes de Novio para Hombre",
  "Trajes de Novia para Mujer",
  "Ropa de Bebé para Niño",
  "Ropa de Bebé para Niña",
  "Zapatillas de Deporte para Hombre",
  "Zapatillas de Deporte para Mujer",
  "Gafas de Sol para Hombre",
  "Gafas de Sol para Mujer",
  "Relojes de Pulsera para Hombre",
  "Relojes de Pulsera para Mujer",
  "Joyas de Plata para Hombre",
  "Joyas de Plata para Mujer",
  "Perfumes de Hombre para Uso Diario",
  "Perfumes de Mujer para Uso Diario",
  "Cremas de Belleza para la Piel",
  "Cremas de Belleza para el Cuerpo",
  "Champú y Acondicionador para el Pelo",
  "Cepillos de Dientes para Adultos",
  "Cepillos de Dientes para Niños",
  "Pastas de Dientes para Adultos",
  "Pastas de Dientes para Niños",
  "Jabones de Baño para Adultos",
  "Jabones de Baño para Niños",
  "Toallas de Baño para Adultos",
  "Toallas de Baño para Niños",
  "Sábanas y Fundas para la Cama",
  "Almohadas y Edredones para la Cama",
  "Muebles de Oficina para el Trabajo",
  "Sillas de Oficina para el Trabajo",
  "Escritorios para el Trabajo",
  "Archivadores para el Trabajo",
  "Impresoras para el Trabajo",
  "Scanners para el Trabajo",
  "Fotocopiadoras para el Trabajo",
  "Cafeteras para el Hogar",
  "Tostadoras para el Hogar",
  "Microondas para el Hogar",
  "Licuadoras para el Hogar",
  "Batidoras para el Hogar",
  "Hornos Eléctricos para el Hogar",
  "Parrillas Eléctricas para el Hogar",
  "Cocinas de Inducción para el Hogar",
  "Refrigeradores para el Hogar",
  "Congeladores para el Hogar",
  "Lavadoras para el Hogar",
  "Secadoras para el Hogar",
  "Aspiradoras para el Hogar",
  "Trapos de Limpieza para el Hogar",
  "Detergentes para el Hogar",
  "Suavizantes para el Hogar",
  "Juguetes de Niños para la Educación",
  "Juegos de Mesa para la Familia",
  "Puzzles para la Familia",
  "Libros de Cuentos para Niños",
  "Libros de Historia para Adultos",
  "Libros de Ciencia para Adultos",
  "Libros de Ficción para Adultos",
  "Música en CD para el Entretenimiento",
  "Películas en DVD para el Entretenimiento",
  "Series de TV en DVD para el Entretenimiento",
  "Instrumentos Musicales para el Entretenimiento",
  "Accesorios de Música para el Entretenimiento",
  "Equipo de Deporte para el Fitness",
  "Bicicletas para el Deporte",
  "Patines para el Deporte",
  "Skateboards para el Deporte",
  "Pelotas de Fútbol para el Deporte",
  "Pelotas de Baloncesto para el Deporte",
  "Pelotas de Tenis para el Deporte",
  "Raquetas de Tenis para el Deporte",
  "Guantes de Béisbol para el Deporte",
  "Bates de Béisbol para el Deporte",
  "Cascos de Fútbol para el Deporte",
  "Protuberancias de Fútbol para el Deporte",
  "Rodilleras de Fútbol para el Deporte",
  "Guantes de Fútbol para el Deporte",
  "Balones de Fútbol para el Deporte",
  "Frutas frescas",
  "Verduras frescas",
  "Carnes frescas",
  "Pescados frescos",
  "Mariscos frescos",
  "Lácteos",
  "Huevos",
  "Panadería",
  "Pastelería",
  "Dulces",
  "Snacks",
  "Bebidas",
  "Café",
  "Té",
  "Chocolate",
  "Aceites",
  "Vinagres",
  "Salsas",
  "Condimentos",
  "Especias",
  "Hierbas",
  "Frutas secas",
  "Nueces",
  "Semillas",
  "Cereales",
  "Harinas",
  "Pasta",
  "Arroz",
  "Legumbres",
  "Carnes procesadas",
  "Pescados procesados",
  "Mariscos procesados",
  "Salsas de tomate",
  "Salsas de soja",
  "Salsas de pescado",
  "Salsas de carne",
  "Salsas de verduras",
  "Salsas de frutas",
  "Mermeladas",
  "Jaleas",
  "Conservas",
  "Ensaladas",
  "Sopas",
  "Cremas",
  "Purés",
  "Salsas de queso",
  "Salsas de crema",
  "Salsas de huevo",
  "Salsas de carne de cerdo",
  "Salsas de carne de ternera",
  "Salsas de carne de pollo",
  "Salsas de pescado",
  "Salsas de marisco",
  "Salsas de verduras",
  "Salsas de frutas",
  "Salsas de nueces",
  "Salsas de semillas",
  "Salsas de granos",
  "Salsas de legumbres",
  "Salsas de cereales",
  "Salsas de harinas",
  "Salsas de pasta",
  "Salsas de arroz",
  "Salsas de legumbres",
  "Salsas de carnes procesadas",
  "Salsas de pescados procesados",
  "Salsas de mariscos procesados",
  "Salsas de verduras procesadas",
  "Salsas de frutas procesadas",
  "Salsas de nueces procesadas",
  "Salsas de semillas procesadas",
  "Salsas de granos procesados",
  "Salsas de legumbres procesadas",
  "Salsas de cereales procesados",
  "Salsas de harinas procesadas",
  "Salsas de pasta procesada",
  "Salsas de arroz procesado",
  "Salsas de legumbres procesadas",
  "Salsas de carnes procesadas",
  "Salsas de pescados procesados",
  "Salsas de mariscos procesados",
  "Salsas de verduras procesadas",
  "Salsas de frutas procesadas",
  "Salsas de nueces procesadas",
  "Salsas de semillas procesadas",
  "Salsas de granos procesados",
  "Salsas de legumbres procesadas",
  "Salsas de cereales procesados",
  "Salsas de harinas procesadas",
  "Salsas de pasta procesada",
  "Salsas de arroz procesado",
  "Salsas de legumbres procesadas",
  "Salsas de carnes procesadas",
  "Salsas de pescados procesados",
  "Salsas de mariscos procesados",
  "Salsas de verduras procesadas",
  "Salsas de frutas procesadas",
  "Salsas de nueces procesadas",
  "Salsas de semillas procesadas",
  "Salsas de granos procesados",
  "Salsas de legumbres procesadas",
  "Salsas de cereales procesados",
  "Salsas de harinas procesadas",
  "Salsas de pasta procesada",
  "Salsas de arroz procesado",
  "Salsas de legumbres procesadas",
  "Salsas de carnes procesadas",
  "Salsas de pescados procesados",
  "Salsas de mariscos procesados",
  "Salsas de frutas procesadas",
  "Salsas de nueces procesadas",
  "Salsas de semillas procesadas",
  "Salsas de granos procesados",
  "Salsas de legumbres procesadas",
  "Salsas de cereales procesados",
  "Salsas de harinas procesadas",
  "Salsas de pasta procesada",
  "Salsas de arroz procesado",
  "Salsas de legumbres procesadas",
  "Salsas de carnes procesadas",
  "Salsas de pescados procesados",
  "Salsas de mariscos procesados",
  "Salsas de verduras procesadas",
  "Salsas de frutas procesadas",
  "Salsas de nueces procesadas",
  "Salsas de semillas procesadas",
  "Salsas de granos procesados",
  "Salsas de legumbres procesadas",
  "Salsas de cereales procesados",
  "Salsas de harinas procesadas",
  "Salsas de pasta procesada",
  "Salsas de arroz procesado",
  "Salsas de legumbres procesadas",
  "Salsas de carnes procesadas",
  "Salsas de pescados procesados",
  "Salsas de mariscos procesados",
  "Salsas de verduras procesadas",
  "Salsas de frutas procesadas",
  "Salsas de nueces procesadas",
  "Salsas de semillas procesadas",
  "Salsas de granos procesados",
  "Salsas de legumbres procesadas",
  "Salsas de cereales procesados",
  "Salsas de harinas procesadas",
  "Salsas de pasta procesada",
  "Salsas de arroz procesado",
  "Salsas de legumbres procesadas",
  "Aceites de oliva",
  "Aceites de girasol",
  "Aceites de maíz",
  "Aceites de soja",
  "Aceites de arroz",
  "Aceites de nueces",
  "Aceites de semillas",
  "Vinagres de vino",
  "Vinagres de manzana",
  "Vinagres de arroz",
  "Vinagres de maíz",
  "Vinagres de soja",
  "Salsas de soja",
  "Salsas de ostras",
  "Salsas de pescado",
  "Salsas de marisco",
  "Salsas de verduras",
  "Salsas de frutas",
  "Salsas de nueces",
  "Salsas de semillas",
  "Salsas de granos",
  "Salsas de legumbres",
  "Salsas de cereales",
  "Salsas de harinas",
  "Salsas de pasta",
  "Salsas de arroz",
  "Salsas de legumbres",
  "Salsas de carnes procesadas",
  "Salsas de pescados procesados",
  "Salsas de mariscos procesados",
  "Salsas de verduras procesadas",
  "Salsas de frutas procesadas",
  "Salsas de nueces procesadas",
  "Salsas de semillas procesadas",
  "Salsas de granos procesados",
  "Salsas de legumbres procesadas",
  "Salsas de cereales procesados",
  "Salsas de harinas procesadas",
  "Salsas de pasta procesada",
  "Salsas de arroz procesado",
  "Salsas de legumbres procesadas",
  "Salsas de carnes procesadas",
  "Salsas de pescados procesados",
  "Salsas de mariscos procesados",
  "Salsas de verduras procesadas",
  "Salsas de frutas procesadas",
  "Salsas de nueces procesadas",
  "Salsas de semillas procesadas",
  "Salsas de granos procesados",
  "Salsas de legumbres procesadas",
  "Salsas de cereales procesados",
  "Salsas de harinas procesadas",
  "Salsas de pasta procesada",
  "Salsas de arroz procesado",
  "Salsas de legumbres procesadas",
  "Salsas de carnes procesadas",
  "Salsas de pescados procesados",
  "Salsas de mariscos procesados",
  "Salsas de verduras procesadas",
  "Salsas de frutas procesadas",
  "Salsas de nueces procesadas",
  "Salsas de semillas procesadas",
  "Salsas de granos procesados",
  "Salsas de legumbres procesadas",
  "Salsas de cereales procesados",
  "Salsas de harinas procesadas",
  "Salsas de pasta procesada",
  "Salsas de arroz procesado",
  "Salsas de legumbres procesadas",
  "Bebidas energéticas",
  "Bebidas isotónicas",
  "Bebidas de proteínas",
  "Bebidas de vitaminas",
  "Bebidas de minerales",
  "Bebidas de hierro",
  "Bebidas de calcio",
  "Bebidas de vitamina C",
  "Bebidas de vitamina D",
  "Bebidas de vitamina E",
  "Bebidas de vitamina K",
  "Bebidas de ácido fólico",
  "Bebidas de biotina",
  "Bebidas de vitamina B12",
  "Bebidas de vitamina B6",
  "Bebidas de vitamina B2",
  "Bebidas de vitamina B1",
  "Bebidas de vitamina A",
  "Bebidas de beta-caroteno",
  "Bebidas de licopeno",
  "Bebidas de luteína",
  "Bebidas de zeaxantina",
  "Bebidas de astaxantina",
  "Bebidas de coenzima Q10",
  "Bebidas de resveratrol",
  "Bebidas de polifenoles",
  "Bebidas de flavonoides",
  "Bebidas de antocianinas",
  "Bebidas de carotenoides",
  "Bebidas de xantofilas",
  "Bebidas de clorofila",
  "Bebidas de ferulato",
  "Bebidas de sinapato",
  "Bebidas de cumarato",
  "Bebidas de cafeato",
  "Bebidas de quercetina",
  "Bebidas de kaempferol",
  "Bebidas de isorhapontigenina",
  "Bebidas de fisetina",
  "Bebidas de naringenina",
  "Bebidas de eriodictiol",
  "Bebidas de hesperidina",
  "Bebidas de diosmina",
  "Bebidas de triptófano",
  "Bebidas de tirosina",
  "Bebidas de fenilalanina",
  "Bebidas de treonina",
  "Bebidas de metionina",
  "Bebidas de valina",
  "Bebidas de leucina",
  "Bebidas de isoleucina",
  "Bebidas de lisina",
  "Bebidas de arginina",
  "Bebidas de glutamina",
  "Bebidas de asparagina",
  "Bebidas de serina",
  "Bebidas de glicina",
  "Bebidas de prolina",
  "Bebidas de hidroxiprolina",
  "Bebidas de alanina",
  "Bebidas de ácido aspártico",
  "Bebidas de ácido glutámico",
  "Bebidas de ácido cítrico",
  "Bebidas de ácido fumárico",
  "Bebidas de ácido málico",
  "Bebidas de ácido tartárico",
  "Bebidas de ácido oxálico",
  "Bebidas de ácido succínico",
  "Bebidas de ácido adípico",
  "Bebidas de ácido subérico",
  "Bebidas de ácido azelaico",
  "Bebidas de ácido sebacico",
  "Bebidas de ácido undecanoico",
  "Bebidas de ácido láctico",
  "Bebidas de ácido pirúvico",
  "Bebidas de ácido acético",
  "Vinagre de vino",
  "Vinagre de manzana",
  "Vinagre de arroz",
  "Vinagre de maíz",
  "Vinagre de soja",
  "Vinagre de trigo",
  "Vinagre de cebada",
  "Vinagre de centeno",
  "Vinagre de avena",
  "Vinagre de quinoa",
  "Vinagre de amaranto",
  "Vinagre de kiwicha",
  "Vinagre de cañihua",
  "Vinagre de chía",
  "Vinagre de lino",
  "Vinagre de girasol",
  "Vinagre de maíz morado",
  "Vinagre de maíz amarillo",
  "Vinagre de maíz blanco",
  "Vinagre de trigo integral",
  "Vinagre de trigo blanco",
  "Vinagre de cebada integral",
  "Vinagre de cebada perlada",
  "Vinagre de avena integral",
  "Vinagre de avena perlada",
  "Vinagre de quinoa integral",
  "Vinagre de quinoa blanca",
  "Vinagre de amaranto integral",
  "Vinagre de amaranto blanco",
  "Vinagre de kiwicha integral",
  "Vinagre de kiwicha blanca",
  "Vinagre de cañihua integral",
  "Vinagre de cañihua blanca",
  "Vinagre de chía integral",
  "Vinagre de chía blanca",
  "Vinagre de lino integral",
  "Vinagre de lino blanco",
  "Vinagre de girasol integral",
  "Vinagre de girasol blanco",
  "Vinagre de maíz morado integral",
  "Vinagre de maíz morado blanco",
  "Vinagre de maíz amarillo integral",
  "Vinagre de maíz amarillo blanco",
  "Vinagre de maíz blanco integral",
  "Vinagre de maíz blanco blanco",
  "Vinagre de trigo integral integral",
  "Vinagre de trigo integral blanco",
  "Vinagre de cebada integral integral",
  "Vinagre de cebada integral perlada",
  "Vinagre de avena integral integral",
  "Vinagre de avena integral perlada",
  "Vinagre de quinoa integral integral",
  "Vinagre de quinoa integral blanca",
  "Vinagre de amaranto integral integral",
  "Vinagre de amaranto integral blanco",
  "Vinagre de kiwicha integral integral",
  "Vinagre de kiwicha integral blanca",
  "Vinagre de cañihua integral integral",
  "Vinagre de cañihua integral blanca",
  "Vinagre de chía integral integral",
  "Vinagre de chía integral blanca",
  "Vinagre de lino integral integral",
  "Vinagre de lino integral blanco",
  "Vinagre de girasol integral integral",
  "Vinagre de girasol integral blanco",
  "Vinagre de maíz morado integral integral",
  "Vinagre de maíz morado integral blanco",
  "Vinagre de maíz amarillo integral integral",
  "Vinagre de maíz amarillo integral blanco",
  "Vinagre de maíz blanco integral integral",
  "Vinagre de maíz blanco integral blanco",
];

export const creteProducts = () => {
    let productRandom = parseInt(Math.random(0, listProducts.length) *listProducts.length);
    return [
        listProducts[productRandom],
        randomPrice(),
        randomStok()
    ]
};
